(SELECT 
`PATIENT_SEX`, `PATIENT_RACE`, `PATIENT_AGE`,  `KTV`, `QB`, `PROG_WEIGHT_LOSS`, `REAL_WEIGHT_LOSS`, `DELTA_WEIGHT`, `PROG_DURATION`, `REAL_DURATION`, `DELTA_DURATION`, `SAP_START`, `SAP_END`, `AVG_SAP`, `DAP_START`, `DAP_END`, `AVG_DAP`, `BLOOD_VOLUME`, `DELTA_BLOOD_FLOW`, `DELTA_UF`, `SYMPTOM_ID`
FROM `dialysisai`.`patient_dialysis_symptom_for_analysis`
WHERE `SYMPTOM_ID` = 1 ORDER BY `SCORE` DESC LIMIT 100)
UNION
(SELECT
`PATIENT_SEX`, `PATIENT_RACE`, `PATIENT_AGE`, `KTV`, `QB`, `PROG_WEIGHT_LOSS`, `REAL_WEIGHT_LOSS`, `DELTA_WEIGHT`, `PROG_DURATION`, `REAL_DURATION`, `DELTA_DURATION`, `SAP_START`, `SAP_END`, `AVG_SAP`, `DAP_START`, `DAP_END`, `AVG_DAP`, `BLOOD_VOLUME`, `DELTA_BLOOD_FLOW`, `DELTA_UF`, `SYMPTOM_ID`
FROM `dialysisai`.`patient_dialysis_symptom_for_analysis`
WHERE `SYMPTOM_ID` = 8 ORDER BY `SCORE` DESC LIMIT 100)